[package]
name = "fmodel-rust"
version = "0.3.0"
edition = "2021"
description = "Accelerate development of compositional, safe, and ergonomic applications/information systems by effectively implementing Event Sourcing and CQRS patterns in Rust."
license = "Apache-2.0"

[dependencies]
async-trait = "0.1.74"

[dev-dependencies]
derive_more = "0.99.17"
tokio = { version = "1.33.0", features = ["rt", "rt-multi-thread", "macros"] }

