name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/setup-rust@v1
        with:
          profile: default
          toolchain: '1.75.0'

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
